function build_model()
% build_model  Programmatically constructs the variable-tilt quadcopter Simulink model.
% Creates tilt_quad_sim.slx from scratch. Any existing file is deleted first
% so you always get a clean rebuild — no stale block state or leftover wiring.
%
% Run params.m first so all PID gains and mission variables are in the workspace.

mdl = 'tilt_quad_sim';

% Make sure the required libraries are open before we add any blocks from them
load_system('simulink');
load_system('slpidlib');
load_system('aerolib6dof2');

% Push all parameters to the base workspace so block expressions resolve
evalin('base', 'params');

if bdIsLoaded(mdl), close_system(mdl, 0); end
if exist([mdl '.slx'], 'file'), delete([mdl '.slx']); end

new_system(mdl);
open_system(mdl);

% Solver: ode45 with variable step. StopTime is driven by sim_time in params.m.
set_param(mdl, ...
    'Solver',          'ode45', ...
    'StopTime',        'sim_time', ...
    'SaveOutput',      'on', ...
    'ReturnWorkspaceOutputs', 'on');

% =====================================================================
%  PLANT SUBSYSTEM
%  Wraps the force/moment computation and the 6DOF rigid-body integrator.
% =====================================================================
plant = [mdl '/Plant'];
add_block('built-in/Subsystem', plant);

add_block('built-in/Inport', [plant '/T_cmd']);
add_block('built-in/Inport', [plant '/beta_cmd'], 'Port', '2');

% This MATLAB Function block takes per-rotor thrust T and tilt angle beta,
% adds gravity (rotated into the body frame) and quadratic aero drag,
% and outputs total force F and moment M for the 6DOF block.
fmBlk = [plant '/ForceMoment'];
add_block('simulink/User-Defined Functions/MATLAB Function', fmBlk);
fmCode = [
"function [F, M] = fcn(T, beta, euler, Vb)" newline ...
"%#codegen" newline ...
"L = 0.225; k_q = 0.01; m = 1.5; g = 9.81;" newline ...
"r = [ L  L 0; -L  L 0; -L -L 0;  L -L 0];" newline ...
"sgn = [1; -1; 1; -1];" newline ...
"F = zeros(3,1); M = zeros(3,1);" newline ...
"for i = 1:4" newline ...
"  Fi = T(i)*[sin(beta(i)); 0; cos(beta(i))];" newline ...
"  ri = r(i,:).';" newline ...
"  F = F + Fi;" newline ...
"  M = M + cross(ri, Fi);" newline ...
"  M(3) = M(3) + sgn(i)*k_q*T(i)*cos(beta(i));" newline ...
"end" newline ...
"% Rotate gravity from earth frame into body frame using the current Euler angles." newline ...
"phi = euler(1); theta = euler(2); psi = euler(3);" newline ...
"cph=cos(phi); sph=sin(phi); cth=cos(theta); sth=sin(theta); cps=cos(psi); sps=sin(psi);" newline ...
"R_eb = [ cth*cps,            cth*sps,           -sth;" newline ...
"        sph*sth*cps - cph*sps, sph*sth*sps + cph*cps, sph*cth;" newline ...
"        cph*sth*cps + sph*sps, cph*sth*sps - sph*cps, cph*cth];" newline ...
"g_earth = [0; 0; -g];" newline ...
"g_body  = R_eb * g_earth;" newline ...
"F = F + m * g_body;" newline ...
"% Quadratic drag opposing body velocity — keeps forward flight from accelerating forever." newline ...
"Cd = [0.05; 0.05; 0.03];" newline ...
"F_drag = -Cd .* Vb .* abs(Vb);" newline ...
"F = F + F_drag;" newline ...
"end"];
setMatlabFcnCode(fmBlk, char(strjoin(fmCode, '')));

% 6DOF Euler Angles block (body-axis, fixed mass)
sixdof = [plant '/SixDOF'];
add_block('aerolib6dof2/6DOF (Euler Angles)', sixdof);
set_param(sixdof, ...
    'mass_0',    '1.5', ...
    'inertia',   'diag([0.02, 0.02, 0.04])', ...
    'xme_0',     '[0 0 0]', ...
    'Vm_0',      '[0 0 0]', ...
    'eul_0',     '[0 0 0]', ...
    'pm_0',      '[0 0 0]');

% Plant outputs — port order matches the 6DOF block
add_block('built-in/Outport', [plant '/Ve']);                      % 1: NED velocity
add_block('built-in/Outport', [plant '/Xe'],    'Port', '2');      % 2: NED position
add_block('built-in/Outport', [plant '/Euler'], 'Port', '3');      % 3: phi theta psi
add_block('built-in/Outport', [plant '/Vb'],    'Port', '4');      % 4: body-frame velocity
add_block('built-in/Outport', [plant '/pqr'],   'Port', '5');      % 5: body angular rates

add_line(plant, 'T_cmd/1',       'ForceMoment/1', 'autorouting', 'on');
add_line(plant, 'beta_cmd/1',    'ForceMoment/2', 'autorouting', 'on');
add_line(plant, 'ForceMoment/1', 'SixDOF/1',      'autorouting', 'on');
add_line(plant, 'ForceMoment/2', 'SixDOF/2',      'autorouting', 'on');
add_line(plant, 'SixDOF/1',      'Ve/1',          'autorouting', 'on');
add_line(plant, 'SixDOF/2',      'Xe/1',          'autorouting', 'on');
add_line(plant, 'SixDOF/3',      'Euler/1',       'autorouting', 'on');
add_line(plant, 'SixDOF/3',      'ForceMoment/3', 'autorouting', 'on');   % Euler feeds back to gravity rotation
add_line(plant, 'SixDOF/5',      'ForceMoment/4', 'autorouting', 'on');   % Vb feeds back to drag
add_line(plant, 'SixDOF/5',      'Vb/1',          'autorouting', 'on');
add_line(plant, 'SixDOF/6',      'pqr/1',         'autorouting', 'on');

% =====================================================================
%  CONTROLLER SUBSYSTEM
%  Altitude, attitude, and velocity PIDs feeding a thrust-tilt allocator.
% =====================================================================
ctrl = [mdl '/Controller'];
add_block('built-in/Subsystem', ctrl);

add_block('built-in/Inport', [ctrl '/Xe']);
add_block('built-in/Inport', [ctrl '/Ve'],    'Port', '2');
add_block('built-in/Inport', [ctrl '/Euler'], 'Port', '3');
add_block('built-in/Inport', [ctrl '/pqr'],   'Port', '4');
add_block('built-in/Inport', [ctrl '/h_des'], 'Port', '5');
add_block('built-in/Inport', [ctrl '/vx_des'],'Port', '6');
add_block('built-in/Inport', [ctrl '/psi_des'],'Port','7');
add_block('built-in/Inport', [ctrl '/Vb'],    'Port', '8');

% Pick the scalar channels we care about from the vector signals
add_block('simulink/Math Operations/Gain', [ctrl '/SelectH']);
set_param([ctrl '/SelectH'],  'Gain', '[0 0 1]', 'Multiplication', 'Matrix(K*u)');
add_block('simulink/Math Operations/Gain', [ctrl '/SelectVz']);
set_param([ctrl '/SelectVz'], 'Gain', '[0 0 1]', 'Multiplication', 'Matrix(K*u)');
add_block('simulink/Math Operations/Gain', [ctrl '/SelectVx']);
set_param([ctrl '/SelectVx'], 'Gain', '[1 0 0]', 'Multiplication', 'Matrix(K*u)');

add_block('built-in/Demux', [ctrl '/DemuxEuler'], 'Outputs', '3');
add_block('built-in/Demux', [ctrl '/DemuxPQR'],   'Outputs', '3');

% Altitude PID: drives Fz_des from height error. Weight feedforward so the
% integrator doesn't have to learn hover trim on its own.
add_block('built-in/Sum',             [ctrl '/AltErr'],  'Inputs', '+-');
add_block('slpidlib/PID Controller',  [ctrl '/AltPID']);
set_param([ctrl '/AltPID'], 'P','Kp_alt','I','Ki_alt','D','Kd_alt', ...
    'UseFilter','on','N','Nf_alt', ...
    'LimitOutput','on', ...
    'UpperSaturationLimit','Fz_pid_max', ...
    'LowerSaturationLimit','Fz_pid_min', ...
    'AntiWindupMode','clamping');
add_block('built-in/Constant',        [ctrl '/Weight'], 'Value', 'm*g');
add_block('built-in/Sum',             [ctrl '/FzSum'],  'Inputs', '++');

% Attitude PIDs — roll and pitch level to zero, yaw tracks psi_des
add_block('built-in/Constant', [ctrl '/PhiRef'],   'Value', '0');
add_block('built-in/Constant', [ctrl '/ThetaRef'], 'Value', '0');
add_block('built-in/Sum', [ctrl '/PhiErr'],   'Inputs', '+-');
add_block('built-in/Sum', [ctrl '/ThetaErr'], 'Inputs', '+-');

% Yaw error wrapped to [-pi, pi] so a 350->10 deg transition doesn't look like a 340 deg step
yawErrBlk = [ctrl '/YawErr'];
add_block('simulink/User-Defined Functions/MATLAB Function', yawErrBlk);
yawErrCode = [
"function e = fcn(psi_des, psi)" newline ...
"%#codegen" newline ...
"d = psi_des - psi;" newline ...
"e = atan2(sin(d), cos(d));" newline ...
"end"];
setMatlabFcnCode(yawErrBlk, char(strjoin(yawErrCode, '')));

add_block('slpidlib/PID Controller', [ctrl '/PhiPID']);
set_param([ctrl '/PhiPID'], 'P','Kp_phi','I','Ki_phi','D','Kd_phi', ...
    'UseFilter','on','N','Nf_att');
add_block('slpidlib/PID Controller', [ctrl '/ThetaPID']);
set_param([ctrl '/ThetaPID'], 'P','Kp_th','I','Ki_th','D','Kd_th', ...
    'UseFilter','on','N','Nf_att');
add_block('slpidlib/PID Controller', [ctrl '/PsiPID']);
set_param([ctrl '/PsiPID'], 'P','Kp_psi','I','Ki_psi','D','Kd_psi', ...
    'UseFilter','on','N','Nf_att', ...
    'LimitOutput','on', ...
    'UpperSaturationLimit','Mz_pid_max', ...
    'LowerSaturationLimit','Mz_pid_min', ...
    'AntiWindupMode','clamping');

% Thrust-tilt allocator: maps (Fx, Fz, Mx, My, Mz) to per-rotor T and beta.
% Altitude always gets priority — horizontal demand is capped to whatever
% rotor capacity is left after satisfying vertical lift.
allocBlk = [ctrl '/Allocator'];
add_block('simulink/User-Defined Functions/MATLAB Function', allocBlk);
allocCode = [
"function [T, beta] = fcn(Fx_des, Fz_des, Mx_des, My_des, Mz_des)" newline ...
"%#codegen" newline ...
"L = 0.225; T_max = 15; beta_max = pi/3;" newline ...
"m = 1.5; g = 9.81; eps = 0.0;" newline ...
"k_q = 0.01;  % must match ForceMoment block" newline ...
"% Start with the vertical component each rotor needs to hold altitude" newline ...
"Tz0 = max(Fz_des,0)/4;" newline ...
"% Spread attitude moments via differential vertical thrust" newline ...
"dTz_pitch = My_des / (4*L);" newline ...
"dTz_roll  = Mx_des / (4*L);" newline ...
"% Yaw via reactive-torque differential — pattern [+,-,+,-] matches ForceMoment" newline ...
"dTz_yaw = Mz_des / (4 * k_q);" newline ...
"sgn_pitch     = [-1; +1; +1; -1];" newline ...
"sgn_roll      = [+1; +1; -1; -1];" newline ...
"sgn_yaw_react = [+1; -1; +1; -1];" newline ...
"Tz = Tz0 + sgn_pitch.*dTz_pitch + sgn_roll.*dTz_roll + sgn_yaw_react.*dTz_yaw;" newline ...
"Tz = max(Tz, 0);" newline ...
"% Share forward thrust equally across all four rotors" newline ...
"Tx0 = Fx_des/4;" newline ...
"Tx = Tx0 * ones(4,1);" newline ...
"% Clamp horizontal thrust so no rotor exceeds T_max after combining with vertical" newline ...
"Tx_geom_cap = sqrt(max(T_max^2 - Tz.^2, 0));" newline ...
"for i = 1:4" newline ...
"  if Tx(i) >  Tx_geom_cap(i), Tx(i) =  Tx_geom_cap(i); end" newline ...
"  if Tx(i) < -Tx_geom_cap(i), Tx(i) = -Tx_geom_cap(i); end" newline ...
"end" newline ...
"T  = sqrt(Tx.^2 + Tz.^2);" newline ...
"beta = atan2(Tx, max(Tz,1e-6));" newline ...
"% Hard limits on thrust magnitude and tilt angle" newline ...
"for i = 1:4" newline ...
"  if T(i) > T_max, T(i) = T_max; end" newline ...
"  if T(i) < 0,     T(i) = 0;     end" newline ...
"  if beta(i) >  beta_max, beta(i) =  beta_max; end" newline ...
"  if beta(i) < -beta_max, beta(i) = -beta_max; end" newline ...
"end" newline ...
"end"];
setMatlabFcnCode(allocBlk, char(strjoin(allocCode, '')));

% Forward-velocity PID: vx_des -> Fx_des
add_block('built-in/Sum',            [ctrl '/VxErr'], 'Inputs', '+-');
add_block('slpidlib/PID Controller', [ctrl '/VxPID']);
set_param([ctrl '/VxPID'], 'P','Kp_vx','I','Ki_vx','D','Kd_vx', ...
    'UseFilter','on','N','Nf_vx', ...
    'LimitOutput','on', ...
    'UpperSaturationLimit','Fx_pid_max', ...
    'LowerSaturationLimit','Fx_pid_min', ...
    'AntiWindupMode','clamping');

add_block('built-in/Mux', [ctrl '/MomentMux'], 'Inputs', '3');

add_block('built-in/Outport', [ctrl '/T_cmd']);
add_block('built-in/Outport', [ctrl '/beta_cmd'], 'Port', '2');

% Wire controller internals
add_line(ctrl, 'Xe/1',        'SelectH/1',    'autorouting', 'on');
add_line(ctrl, 'Ve/1',        'SelectVz/1',   'autorouting', 'on');
add_line(ctrl, 'Vb/1',        'SelectVx/1',   'autorouting', 'on');
add_line(ctrl, 'vx_des/1',    'VxErr/1',      'autorouting', 'on');
add_line(ctrl, 'SelectVx/1',  'VxErr/2',      'autorouting', 'on');
add_line(ctrl, 'VxErr/1',     'VxPID/1',      'autorouting', 'on');
add_line(ctrl, 'Euler/1',     'DemuxEuler/1', 'autorouting', 'on');
add_line(ctrl, 'pqr/1',       'DemuxPQR/1',   'autorouting', 'on');

add_line(ctrl, 'h_des/1',    'AltErr/1',  'autorouting', 'on');
add_line(ctrl, 'SelectH/1',  'AltErr/2',  'autorouting', 'on');
add_line(ctrl, 'AltErr/1',   'AltPID/1',  'autorouting', 'on');
add_line(ctrl, 'AltPID/1',   'FzSum/1',   'autorouting', 'on');
add_line(ctrl, 'Weight/1',   'FzSum/2',   'autorouting', 'on');

add_line(ctrl, 'PhiRef/1',     'PhiErr/1',   'autorouting', 'on');
add_line(ctrl, 'DemuxEuler/1', 'PhiErr/2',   'autorouting', 'on');
add_line(ctrl, 'PhiErr/1',     'PhiPID/1',   'autorouting', 'on');
add_line(ctrl, 'ThetaRef/1',   'ThetaErr/1', 'autorouting', 'on');
add_line(ctrl, 'DemuxEuler/2', 'ThetaErr/2', 'autorouting', 'on');
add_line(ctrl, 'ThetaErr/1',   'ThetaPID/1', 'autorouting', 'on');
add_line(ctrl, 'psi_des/1',    'YawErr/1',   'autorouting', 'on');
add_line(ctrl, 'DemuxEuler/3', 'YawErr/2',   'autorouting', 'on');
add_line(ctrl, 'YawErr/1',     'PsiPID/1',   'autorouting', 'on');

add_line(ctrl, 'PhiPID/1',   'MomentMux/1', 'autorouting', 'on');
add_line(ctrl, 'ThetaPID/1', 'MomentMux/2', 'autorouting', 'on');
add_line(ctrl, 'PsiPID/1',   'MomentMux/3', 'autorouting', 'on');

add_block('built-in/Demux', [ctrl '/DemuxM'], 'Outputs', '3');
add_line(ctrl, 'MomentMux/1', 'DemuxM/1',     'autorouting', 'on');

add_line(ctrl, 'VxPID/1',   'Allocator/1', 'autorouting', 'on');
add_line(ctrl, 'FzSum/1',   'Allocator/2', 'autorouting', 'on');
add_line(ctrl, 'DemuxM/1',  'Allocator/3', 'autorouting', 'on');
add_line(ctrl, 'DemuxM/2',  'Allocator/4', 'autorouting', 'on');
add_line(ctrl, 'DemuxM/3',  'Allocator/5', 'autorouting', 'on');

% Rate limiters prevent step commands — rotors spool up and servos move at finite speed
add_block('simulink/Discontinuities/Rate Limiter', [ctrl '/T_RateLim']);
set_param([ctrl '/T_RateLim'], ...
    'RisingSlewLimit',  'T_rate_max', ...
    'FallingSlewLimit', '-T_rate_max');
add_block('simulink/Discontinuities/Rate Limiter', [ctrl '/Beta_RateLim']);
set_param([ctrl '/Beta_RateLim'], ...
    'RisingSlewLimit',  'beta_rate_max', ...
    'FallingSlewLimit', '-beta_rate_max');

add_line(ctrl, 'Allocator/1',    'T_RateLim/1',    'autorouting', 'on');
add_line(ctrl, 'T_RateLim/1',    'T_cmd/1',         'autorouting', 'on');
add_line(ctrl, 'Allocator/2',    'Beta_RateLim/1', 'autorouting', 'on');
add_line(ctrl, 'Beta_RateLim/1', 'beta_cmd/1',      'autorouting', 'on');

% =====================================================================
%  TOP-LEVEL WIRING
%  Guidance FSM, mission constants, signal routing, and logging.
% =====================================================================
% The guidance FSM is a discrete MATLAB Function block running at 100 Hz.
% It steps through six phases: TAKEOFF -> ALIGN -> CRUISE -> HOVER -> DESCEND -> LANDED.
guidBlk = [mdl '/Guidance'];
add_block('simulink/User-Defined Functions/MATLAB Function', guidBlk);
guidCode = [
"function [vx_des, psi_des, h_des, state_out, stop_sim] = fcn(t, Xe, Euler, target, v_c, h_cruise, t_takeoff, hover_time, descend_rate, h_land, decel_frac, psi_lock_dist, psi_hold_t, h_tol, psi_tol, arrive_tol, min_approach_speed, kp_pos_hold, Vb, v_recover_max)" newline ...
"%#codegen" newline ...
"persistent state t_state_entry t_prev psi_locked dist0 h_des_prev t_align_ok t_settle_ok inited" newline ...
"if isempty(inited)" newline ...
"  state = 1; t_state_entry = 0; t_prev = 0;" newline ...
"  psi_locked = Euler(3); dist0 = 1;" newline ...
"  h_des_prev = 0; t_align_ok = -1; t_settle_ok = -1; inited = true;" newline ...
"end" newline ...
"dt = max(t - t_prev, 0);" newline ...
"dx = target(1) - Xe(1);" newline ...
"dy = target(2) - Xe(2);" newline ...
"dist = hypot(dx, dy);" newline ...
"psi_target = atan2(dy, dx);" newline ...
"d = psi_target - Euler(3);" newline ...
"heading_err = atan2(sin(d), cos(d));" newline ...
"h_meas = Xe(3);" newline ...
"vx_des = 0;" newline ...
"psi_des = psi_locked;" newline ...
"h_des = h_des_prev;" newline ...
"switch state" newline ...
"  case 1  % TAKEOFF: ramp altitude using a smoothstep so climb rate is zero at the top" newline ...
"    psi_des = psi_locked;" newline ...
"    if t_takeoff > 0" newline ...
"      tau = min(max((t - t_state_entry) / t_takeoff, 0), 1);" newline ...
"      h_des = h_cruise * (3*tau^2 - 2*tau^3);" newline ...
"    else" newline ...
"      h_des = h_cruise;" newline ...
"    end" newline ...
"    settle_ok = (t - t_state_entry) >= t_takeoff && abs(h_meas - h_cruise) < h_tol && abs(Vb(3)) < 0.15;" newline ...
"    if settle_ok" newline ...
"      if t_settle_ok < 0, t_settle_ok = t; end" newline ...
"    else" newline ...
"      t_settle_ok = -1;" newline ...
"    end" newline ...
"    if t_settle_ok >= 0 && (t - t_settle_ok) >= 1.5" newline ...
"      state = 2; t_state_entry = t; t_align_ok = -1; t_settle_ok = -1;" newline ...
"    end" newline ...
"  case 2  % ALIGN: rotate to face the target before accelerating forward" newline ...
"    psi_des = psi_target;" newline ...
"    h_des = h_cruise;" newline ...
"    if abs(heading_err) < psi_tol" newline ...
"      if t_align_ok < 0, t_align_ok = t; end" newline ...
"    else" newline ...
"      t_align_ok = -1;" newline ...
"    end" newline ...
"    if (t_align_ok >= 0 && (t - t_align_ok) >= psi_hold_t) || (t - t_state_entry) >= 12.0" newline ...
"      state = 3; t_state_entry = t;" newline ...
"      dist0 = max(dist, 1);" newline ...
"      psi_locked = psi_target;" newline ...
"    end" newline ...
"  case 3  % CRUISE: heading frozen; approach with bang-bang braking" newline ...
"    psi_des = psi_locked;" newline ...
"    h_des = h_cruise;" newline ...
"    signed_dist = dx*cos(psi_locked) + dy*sin(psi_locked);" newline ...
"    vbx = Vb(1);" newline ...
"    if signed_dist > 1.5" newline ...
"      a_brake = 3.0;" newline ...
"      stop_d = max(vbx,0)^2 / (2*a_brake);" newline ...
"      if signed_dist > stop_d + 2*arrive_tol" newline ...
"        vx_des = v_c * min((t - t_state_entry)/1.5, 1);  % ease in over 1.5 s to avoid an altitude lurch" newline ...
"      else" newline ...
"        vx_des = 0;" newline ...
"      end" newline ...
"    elseif signed_dist < -1.5" newline ...
"      % Gone past the target — gentle reverse tilt to come back" newline ...
"      vx_des = max(-v_recover_max, kp_pos_hold * signed_dist);" newline ...
"    else" newline ...
"      % Inside the terminal window: P position hold" newline ...
"      vx_des = max(-v_recover_max, min(v_recover_max, kp_pos_hold * signed_dist));" newline ...
"    end" newline ...
"    if (abs(signed_dist) < arrive_tol && abs(vbx) < 0.05) || ((t - t_state_entry) >= 25.0 && abs(signed_dist) < 4*arrive_tol) || ((t - t_state_entry) >= 50.0)" newline ...
"      state = 4; t_state_entry = t;" newline ...
"    end" newline ...
"  case 4  % HOVER: hold position over target for a set dwell time" newline ...
"    psi_des = psi_locked;" newline ...
"    h_des = h_cruise;" newline ...
"    signed_dist = dx*cos(psi_locked) + dy*sin(psi_locked);" newline ...
"    vx_des = max(-0.2, min(0.2, kp_pos_hold * signed_dist));" newline ...
"    if (t - t_state_entry) >= hover_time" newline ...
"      state = 5; t_state_entry = t;" newline ...
"    end" newline ...
"  case 5  % DESCEND: slowly lower altitude while staying above the target" newline ...
"    psi_des = psi_locked;" newline ...
"    h_des = max(h_land, h_des_prev - descend_rate * dt);" newline ...
"    signed_dist = dx*cos(psi_locked) + dy*sin(psi_locked);" newline ...
"    vx_des = max(-0.2, min(0.2, kp_pos_hold * signed_dist));" newline ...
"    if h_des <= h_land + 0.01 || (t - t_state_entry) >= ((h_cruise - h_land)/max(descend_rate,0.05) + 15.0)" newline ...
"      state = 6; t_state_entry = t;" newline ...
"    end" newline ...
"  otherwise  % LANDED: keep the drone softly on the spot" newline ...
"    psi_des = psi_locked;" newline ...
"    h_des = h_land;" newline ...
"    signed_dist = dx*cos(psi_locked) + dy*sin(psi_locked);" newline ...
"    vx_des = max(-0.15, min(0.15, kp_pos_hold * signed_dist));" newline ...
"end" newline ...
"h_des_prev = h_des;" newline ...
"t_prev = t;" newline ...
"state_out = double(state);" newline ...
"stop_sim = double(state == 6 && (t - t_state_entry) >= 6.0);" newline ...
"end"];
setMatlabFcnCode(guidBlk, char(strjoin(guidCode, '')));

% The FSM uses persistent state so it needs a fixed sample time
gchart = sfroot().find('-isa', 'Stateflow.EMChart', '-and', 'Path', guidBlk);
gchart.ChartUpdate = 'DISCRETE';
gchart.SampleTime  = '0.01';

% Mission constants from base workspace (set in params.m)
add_block('simulink/Sources/Clock',    [mdl '/SimClock']);
add_block('simulink/Sources/Constant', [mdl '/TargetXY'],     'Value', 'target_xy');
add_block('simulink/Sources/Constant', [mdl '/VCruise'],      'Value', 'v_cruise');
add_block('simulink/Sources/Constant', [mdl '/HCruiseC'],     'Value', 'h_cruise');
add_block('simulink/Sources/Constant', [mdl '/TTakeoffC'],    'Value', 't_takeoff');
add_block('simulink/Sources/Constant', [mdl '/HoverTimeC'],   'Value', 'hover_time');
add_block('simulink/Sources/Constant', [mdl '/DescendRateC'], 'Value', 'descend_rate');
add_block('simulink/Sources/Constant', [mdl '/HLandC'],       'Value', 'h_land');
add_block('simulink/Sources/Constant', [mdl '/DecelFracC'],   'Value', 'decel_frac');
add_block('simulink/Sources/Constant', [mdl '/PsiLockDistC'], 'Value', 'psi_lock_dist');
add_block('simulink/Sources/Constant', [mdl '/PsiHoldTC'],    'Value', 'psi_hold_t');
add_block('simulink/Sources/Constant', [mdl '/HTolC'],        'Value', 'h_tol');
add_block('simulink/Sources/Constant', [mdl '/PsiTolC'],      'Value', 'psi_tol');
add_block('simulink/Sources/Constant', [mdl '/ArriveTolC'],   'Value', 'arrive_tol');
add_block('simulink/Sources/Constant', [mdl '/MinApproachC'], 'Value', 'min_approach_speed');
add_block('simulink/Sources/Constant', [mdl '/KpPosHoldC'],   'Value', 'kp_pos_hold');
add_block('simulink/Sources/Constant', [mdl '/VRecoverC'],    'Value', 'v_recover_max');

% Wire Guidance inputs
add_line(mdl, 'SimClock/1',     'Guidance/1',  'autorouting', 'on');
add_line(mdl, 'Plant/2',        'Guidance/2',  'autorouting', 'on');
add_line(mdl, 'Plant/3',        'Guidance/3',  'autorouting', 'on');
add_line(mdl, 'TargetXY/1',     'Guidance/4',  'autorouting', 'on');
add_line(mdl, 'VCruise/1',      'Guidance/5',  'autorouting', 'on');
add_line(mdl, 'HCruiseC/1',     'Guidance/6',  'autorouting', 'on');
add_line(mdl, 'TTakeoffC/1',    'Guidance/7',  'autorouting', 'on');
add_line(mdl, 'HoverTimeC/1',   'Guidance/8',  'autorouting', 'on');
add_line(mdl, 'DescendRateC/1', 'Guidance/9',  'autorouting', 'on');
add_line(mdl, 'HLandC/1',       'Guidance/10', 'autorouting', 'on');
add_line(mdl, 'DecelFracC/1',   'Guidance/11', 'autorouting', 'on');
add_line(mdl, 'PsiLockDistC/1', 'Guidance/12', 'autorouting', 'on');
add_line(mdl, 'PsiHoldTC/1',    'Guidance/13', 'autorouting', 'on');
add_line(mdl, 'HTolC/1',        'Guidance/14', 'autorouting', 'on');
add_line(mdl, 'PsiTolC/1',      'Guidance/15', 'autorouting', 'on');
add_line(mdl, 'ArriveTolC/1',   'Guidance/16', 'autorouting', 'on');
add_line(mdl, 'MinApproachC/1', 'Guidance/17', 'autorouting', 'on');
add_line(mdl, 'KpPosHoldC/1',   'Guidance/18', 'autorouting', 'on');
add_line(mdl, 'Plant/4',        'Guidance/19', 'autorouting', 'on');
add_line(mdl, 'VRecoverC/1',    'Guidance/20', 'autorouting', 'on');

% Plant -> Controller
add_line(mdl, 'Plant/2',    'Controller/1', 'autorouting', 'on');
add_line(mdl, 'Plant/1',    'Controller/2', 'autorouting', 'on');
add_line(mdl, 'Plant/3',    'Controller/3', 'autorouting', 'on');
add_line(mdl, 'Plant/5',    'Controller/4', 'autorouting', 'on');
add_line(mdl, 'Guidance/3', 'Controller/5', 'autorouting', 'on');
add_line(mdl, 'Guidance/1', 'Controller/6', 'autorouting', 'on');
add_line(mdl, 'Guidance/2', 'Controller/7', 'autorouting', 'on');
add_line(mdl, 'Plant/4',    'Controller/8', 'autorouting', 'on');

% Controller -> Plant
add_line(mdl, 'Controller/1', 'Plant/1', 'autorouting', 'on');
add_line(mdl, 'Controller/2', 'Plant/2', 'autorouting', 'on');

% Logging — one To Workspace block per key signal
add_logging_block(mdl, 'Plant/2',    'position',     'Xe');
add_logging_block(mdl, 'Plant/1',    'velocity',     'Ve');
add_logging_block(mdl, 'Plant/3',    'euler',        'Euler');
add_logging_block(mdl, 'Plant/4',    'vb',           'Vb');
add_logging_block(mdl, 'Plant/5',    'pqr',          'PQR');
add_logging_block(mdl, 'Controller/1', 'T_log',      'Tlog');
add_logging_block(mdl, 'Controller/2', 'beta_log',   'BetaLog');
add_logging_block(mdl, 'Guidance/1',   'vx_des_log', 'VxDesLog');
add_logging_block(mdl, 'Guidance/2',   'psi_des_log','PsiDesLog');
add_logging_block(mdl, 'Guidance/3',   'h_des_log',  'HDesLog');
add_logging_block(mdl, 'Guidance/4',   'state_log',  'StateLog');

% Stop simulation automatically a few seconds after touchdown
add_block('simulink/Sinks/Stop Simulation', [mdl '/StopSim']);
add_line(mdl, 'Guidance/5', 'StopSim/1', 'autorouting', 'on');

% Extra diagnostic logs inside the Controller — useful for tuning
add_block('simulink/Sinks/To Workspace', [ctrl '/FzDesLog']);
set_param([ctrl '/FzDesLog'], 'VariableName', 'FzDes', 'SaveFormat', 'Timeseries');
add_line(ctrl, 'FzSum/1', 'FzDesLog/1', 'autorouting', 'on');

add_block('simulink/Sinks/To Workspace', [ctrl '/HmeasLog']);
set_param([ctrl '/HmeasLog'], 'VariableName', 'Hmeas', 'SaveFormat', 'Timeseries');
add_line(ctrl, 'SelectH/1', 'HmeasLog/1', 'autorouting', 'on');

add_block('simulink/Sinks/To Workspace', [ctrl '/AltErrLog']);
set_param([ctrl '/AltErrLog'], 'VariableName', 'AltErr', 'SaveFormat', 'Timeseries');
add_line(ctrl, 'AltErr/1', 'AltErrLog/1', 'autorouting', 'on');

add_block('simulink/Sinks/To Workspace', [ctrl '/FxDesLog']);
set_param([ctrl '/FxDesLog'], 'VariableName', 'FxDes', 'SaveFormat', 'Timeseries');
add_line(ctrl, 'VxPID/1', 'FxDesLog/1', 'autorouting', 'on');

% Auto-arrange so the block diagram is readable
Simulink.BlockDiagram.arrangeSystem(mdl);
Simulink.BlockDiagram.arrangeSystem(plant);
Simulink.BlockDiagram.arrangeSystem(ctrl);

save_system(mdl);
fprintf('Build complete: %s.slx\n', mdl);
end

% =====================================================================
function setMatlabFcnCode(blkPath, code)
% Inject MATLAB code into a MATLAB Function (Stateflow EMChart) block.
    rt    = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blkPath);
    if isempty(chart)
        open_system(blkPath);
        chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blkPath);
    end
    chart.Script = code;
end

function add_logging_block(mdl, srcPort, blkName, varName)
% Add a To Workspace block and connect it to a signal already on the diagram.
    blkPath = [mdl '/' blkName];
    add_block('simulink/Sinks/To Workspace', blkPath);
    set_param(blkPath, 'VariableName', varName, 'SaveFormat', 'Timeseries');
    tokens  = regexp(srcPort, '^([^/]+)/(\d+)$', 'tokens', 'once');
    portIdx = str2double(tokens{2});
    add_line(mdl, [tokens{1} '/' num2str(portIdx)], [blkName '/1'], 'autorouting', 'on');
end
